### ISSUE TITLE
Client crashing when disconnecting UI

### ISSUE THREAD

**Issue by karimcitoh** [PRINTR3D/formide-client#115]
```
/Users/karimcito/Documents/GitHub/formide-client/node_modules/winston/node_modules/cycle/cycle.js:90
                nu = {};
                   ^

RangeError: Maximum call stack size exceeded
    at derez (/Users/karimcito/Documents/GitHub/formide-client/node_modules/winston/node_modules/cycle/cycle.js:90:20)
    at Object.decycle (/Users/karimcito/Documents/GitHub/formide-client/node_modules/winston/node_modules/cycle/cycle.js:101:6)
    at Object.exports.log (/Users/karimcito/Documents/GitHub/formide-client/node_modules/winston/lib/winston/common.js:117:95)
    at Console.log (/Users/karimcito/Documents/GitHub/formide-client/node_modules/winston/lib/winston/transports/console.js:64:19)
    at emit (/Users/karimcito/Documents/GitHub/formide-client/node_modules/winston/lib/winston/logger.js:175:17)
    at /Users/karimcito/Documents/GitHub/formide-client/node_modules/winston/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/Users/karimcito/Documents/GitHub/formide-client/node_modules/winston/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/Users/karimcito/Documents/GitHub/formide-client/node_modules/winston/node_modules/async/lib/async.js:110:9)
    at Logger.log (/Users/karimcito/Documents/GitHub/formide-client/node_modules/winston/lib/winston/logger.js:203:9)
    at Function.target.(anonymous function) (/Users/karimcito/Documents/GitHub/formide-client/node_modules/winston/lib/winston/common.js:44:18)
    at Function._writeLogToConsole [as error] (/Users/karimcito/Documents/GitHub/formide-client/node_modules/captains-log/lib/write.js:78:16)
    at Connection.<anonymous> (/Users/karimcito/Documents/GitHub/formide-client/core/utils/websocket/index.js:61:19)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at Connection.sendText (/Users/karimcito/Documents/GitHub/formide-client/node_modules/nodejs-websocket/Connection.js:135:7)
    at EventEmitter.<anonymous> (/Users/karimcito/Documents/GitHub/formide-client/core/utils/websocket/index.js:42:14)
    at EventEmitter.emit (/Users/karimcito/Documents/GitHub/formide-client/node_modules/eventemitter2/lib/eventemitter2.js:278:22)
    at EventTransport.log (/Users/karimcito/Documents/GitHub/formide-client/core/utils/log.js:23:19)
    at emit (/Users/karimcito/Documents/GitHub/formide-client/node_modules/winston/lib/winston/logger.js:175:17)
    at /Users/karimcito/Documents/GitHub/formide-client/node_modules/winston/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)

```

**Comment by ChrisTerBeke** [comment]
Maybe an event listener not being closed?

**Comment by ChrisTerBeke** [comment]
Might be fixed now. Not sure what the exact issue is, since it seems to be triggered in a dependency that we use for logging. `RangeError: Maximum call stack size exceeded` usually means the data is too big to handle.

**Comment by karimcitoh** [comment]
It still crashes. It only happens when I quit Native UI.

**Comment by ChrisTerBeke** [comment]
FIXED IT!
